### ISSUE TITLE
[Bug] Copied/pasted Emoji ID is incorrect format

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#190]
Actual behavior:

1. Copied Emoji ID from profile screen on mobile wallet
2. Pasted into SMS and email
3. On both, this URL appeared with some emojis that don't appear to be in the standard char set
tari://rincewind/eid/🐏👿🦴😻😘😺🥶🦙👽👺💩🦵🥶😓🙈😙👕👟😍👂😒🕶🙁💦🤣👌😆🐿😤🙉👏😡🦓

Expected behavior:
- No URL should appear, only the emoji ID
- Emoji ID should consist of chars broadly supported
- Pipes should appear every 3 emojis across the app and also when copied/pasted, just like phone numbers always appear with XXX-XXX-XXXX but have the special chars stripped out in the DB  🙁💦🤣|👌😆 🙁|💦🤣 🙁|💦🤣🤣 etc etc

Device:
- iPhone X running iOS 13

**Comment by Jasonvdb** [comment]
@talmahaj this what in the spec though? https://github.com/tari-project/tari/issues/1333

**Comment by talmahaj** [comment]
We ixnay’d the deep link proposal in favor of the 33 emoji ID, so not sure why this was reopened. I’ll talk to Cayle.

**Comment by CjS77** [comment]
What removed what including the hex public key. 

The argument for keeping the URI format is that is offers contextual info that has several benefits:
* We can differentiate between different networks (mainnet / testnet 1 / testnet 2)
* This format is extendible, so we can add things like preferred alias in the link in the future and have the app interpret that info immediately without user input.
* The URL can be registered on devices, so that clicking it (from whatsapp, browser etc) will immediately take you to the "Send To" page in the app.

Further, I think it's more natural for a user to grok this:
tari://rincewind/eid/🐏👿🦴😻😘😺🥶🦙👽👺💩🦵🥶😓🙈😙👕👟😍👂😒🕶🙁💦🤣👌😆🐿😤🙉👏😡🦓
(Oh! it's a tari address)

than this:
🐏👿🦴😻😘😺🥶🦙👽👺💩🦵🥶😓🙈😙👕👟😍👂😒🕶🙁💦🤣👌😆🐿😤🙉👏😡🦓
(Shit, my toddler has been playing with my phone again)

You have another comment about pipe characters. We can add these into links no problem and agree that it will aid readability (at the expense of making the string longer)

**Comment by talmahaj** [comment]
@Jasonvdb @kukabi  Discussed with @CjS77 and we agreed there are two separate features and UX patterns being discussed here:

"Copy" --> Users expect that exactly what appears in the interface next to the Copy action will be copied to the clipboard
"Share" (or link icon) --> Users expect that a URL will be copied

Currently, we only have the UX designed for the "copy" feature, so it should behave as spec'd in the original tickets for this feature, which is all already included in the ticket description above.

I've added a separate ticket in our github backlog for the "Share" feature, which I agree is very useful, but requires UX work and can be done as a fast follow after launch. Before we expose a URL to users, we'd also want to probably make them appear as web URLs to be more user-friendly (since other consumer apps always do it this way; they don't expose the native app URI schema in their links because it's unfamiliar)

**Comment by talmahaj** [comment]
Just in case it isn't clear, deep links are still relevant for the QR code, just not for the Copy button
