### ISSUE TITLE
[Enhancement] Updated Splash Screen tweaks (I know, I know)

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#216]
@talmahaj commented on [Sun Mar 29 2020](https://github.com/tari-project/tari/issues/1622)

Are you sick of tweaking the splash screen yet? No? In that case, don't worry, do I have some thrilling updates for you!

Updated design specs: https://drive.google.com/file/d/1jTX3THBmfqeKGQOIa3K3yuogIeXXlTVA/view?usp=sharing

Acceptance Criteria:
- Change headline to read "The future of digital assets starts here." (Note that this is DIFFERENT from the design above)
- Remove the current small text under heading on all devices per the design above
- On devices (Android and iOS) with >800pt height, e.g. iPhone X and above for iOS, use measurements in "Generic Guide" and ensure orb is vertically centered between logo and headline 
- For devices even taller than the one in "Generic Guide" (812pt), the measurements and spacing should stay exactly the same EXCEPT the orb graphic should scale up proportionately
- On devices (Android and iOS) with <800pt height, use measurements in "Guide for smaller devices" screen linked above

**Comment by Anziskavds** [comment]
@kukabi I had some issues with cards having old information in the descriptions and designs attached. Before I test this I would just like to confirm with you first if all the information provided in the description is still the same or has something changed?

cc @Tas4tari

**Comment by Anziskavds** [comment]
The first two points tested successfully on iOS. I tested on an iPhone 7. I'm currently unable to test the last 3 points because I don't have a bigger device to use for testing. The app on Browserstack isn't working and I still need some tool to test the measurements on the screen. 
@Jasonvdb @Tas4tari @talmahaj 

![IMG_859592549DF0-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/48caa154-da3b-4249-8c81-80dd170a2c15)

**Comment by talmahaj** [comment]
@Anziskavds Good news, I remember testing this myself and it passing QA a few months ago, not sure why I forgot to close it! Sorry!
