### ISSUE TITLE
Connectivity issue error modal copy change

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#254]
@talmahaj commented on [Mon Apr 06 2020](https://github.com/tari-project/wallet-android/issues/265)

"It's not you, it's us" ---> "It's not you, it's the network"

Thanks for the feedback @Jasonvdb !

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.1.12. (iPhone 7). I have no connectivity on my device and I haven't received any error message.

![IMG_26505A27EC61-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/762feea2-fb66-468e-a4af-e561d2743209)

**Comment by Jasonvdb** [comment]
@Anziskavds I think you're only supposed to get this error when you try send. Is that right @talmahaj ?

**Comment by talmahaj** [comment]
Yes you have to hit the Send tXTR button if I remember correctly @Anziskavds

**Comment by Tas4tari** [comment]
@Anziskavds Can you try replicating the error by hitting the send tXTR button and letting us know if this is still an issue. I will move this into UAT in the interim

**Comment by Anziskavds** [comment]
Tested on iOS on version 0.4.0(131) on an iPhone 7. As per my understanding, this ticket is created for the change of copy on this error message. When I first tested I misunderstood this. I have received the error message by testing this now and the copy is changed and reads correctly as expected in the above description. I also saw that the error message was received because of the base node sync failed.

![IMG_0805 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6586704e-5734-4f40-8e11-6b7629038b23)

![IMG_0804.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8cdc96f2-1a7b-45ee-910d-b6f4c743dcfb)


cc @Jasonvdb @Tas4tari @talmahaj Please advise?

**Comment by Anziskavds** [comment]
@Jasonvdb @Tas4tari @talmahaj Any feedback yet on my above question?

**Comment by Tas4tari** [comment]
@Anziskavds This is correct, because the base node is ultimately a network failure when it fails to sync. @kukabi correct me if I'm wrong

**Comment by Jasonvdb** [comment]
Seems right to me

**Comment by kukabi** [comment]
Same here.

> Seems right to me

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0 (132) on an iPhone 7.

![IMG_0805 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6586704e-5734-4f40-8e11-6b7629038b23)

![IMG_0804.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8cdc96f2-1a7b-45ee-910d-b6f4c743dcfb)
