### ISSUE TITLE
[Feature] Ability to include default amount and note in deep link

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#306]
@talmahaj commented on [Wed Apr 22 2020](https://github.com/tari-project/wallet-android/issues/297)

@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1742)

**Comment by Anziskavds** [comment]
@Jasonvdb @kukabi What deep link can I use for testing?

**Comment by Jasonvdb** [comment]
@Anziskavds these 2 should pre populate the amount and the note values:

[tari://rincewind/eid/🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈?amount=32.1&note=hi%20there
](tari://rincewind/eid/🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈?amount=32.1&note=hi%20there
)

[tari://rincewind/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a?amount=32.1note=hi%20there](tari://rincewind/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a?amount=32.1note=hi%20there)

**Comment by Anziskavds** [comment]
Tested on iOS version 0.1.12 (iPhone 7).

I used the below steps to test "tari://rincewind/eid/🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈?amount=32.1¬e=hi%20there":

1. Copied tari://rincewind/eid/🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈?amount=32.1¬e=hi%20there and I have added it in the QR Code generator 
2. I have scanned the QR Code on my laptop from the iOS device
3. The app opened but I received the below error message.

![IMG_1539A5990239-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4b4c560e-8303-4acd-a5d1-e9ce1e95cc8f)

I used the below steps to test "tari://rincewind/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a?amount=32.1note=hi%20there"

1. Copied tari://rincewind/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a?amount=32.1note=hi%20there and I have added it in the QR Code generator 
2. I have scanned the QR Code on my laptop from the iOS device
3. The app opened and I received the below screen after the app opened. 

Is this the expected behavior? @Jasonvdb @kukabi 

![IMG_4D6716A5B776-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ba9dc276-682d-456e-a5c2-bc2152eddeec)

**Comment by Jasonvdb** [comment]
@Anziskavds please screenshot and post the QR code here you scanned, I'll try debug

**Comment by Anziskavds** [comment]
@Jasonvdb ![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e6771508-7cfb-4164-9440-058f9b8f548c)

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ca03a680-816b-4d6f-ba14-ad45ec53afd9)

**Comment by talmahaj** [comment]
@Jasonvdb  The deep link *without* the parameters is working just fine for me, but as soon as I add either parameter or both I get the "could not get emoji from link" error.

I noticed that the & was missing from the pubkey URL, and I wasn't sure it was intentional, but adding that back didn't fix it either..

**Comment by talmahaj** [comment]
Also didn't this already go to prod? @Anziskavds pls clearly escalate it on standup if there are tickets in a release that haven't passed QA before we hit the button

**Comment by Jasonvdb** [comment]
@Anziskavds @talmahaj so 2 things went wrong here.

First is I copied this links directly from the code’s unit tests and tried to make a clickable link here in github's markdown. That failed and messed up the `&`.

Second thing that went wrong was this QR generator was percent encoding the emojis. Which turned our pretty emoji deep link into this: 
`tari://rincewind/eid/%F0%9F%90%92%F0%9F%90%91%F0%9F%8D%94%F0%9F%94%A7%E2%9D%8C%F0%9F%91%82%F0%9F%A6%92%F0%9F%92%87%F0%9F%94%8B%F0%9F%92%A5%F0%9F%8D%B7%F0%9F%8D%BA%F0%9F%91%94%F0%9F%98%B7%F0%9F%90%B6%F0%9F%A7%A2%F0%9F%A4%A9%F0%9F%92%A5%F0%9F%8E%BE%F0%9F%8E%B2%F0%9F%8F%80%F0%9F%A4%A0%F0%9F%92%AA%F0%9F%91%AE%F0%9F%A4%AF%F0%9F%8E%81%F0%9F%92%89%F0%9F%8C%9E%F0%9F%8D%89%F0%9F%A4%B7%F0%9F%8D%A6%F0%9F%91%BD%F0%9F%94%88?amount=32.1&note=hi%20there`

I’ve added a fix that will catch this, will be in the next release. But I would suggest in the future if we ever host a QR code somewhere that we just stick to the hex public key. It’ll be much safer and it’s not like users ever see the actual contents of a QR code.

I made this little test site to check this so this can be used for any future tests for both iOS and Android. It has QR codes and clickable deeplinks so this test site can can be opened on phones and then just tap the links you want to test.

Hosted here: [http://aurora-deep-links.surge.sh/](http://aurora-deep-links.surge.sh/)

Code for any future updates: [deeplinks-test.zip](https://github.com/tari-project/wallet-ios/files/4700889/deeplinks-test.zip)

**Comment by talmahaj** [comment]
@Jasonvdb No issues now! Works perfectly, woohoo!

**Comment by talmahaj** [comment]
You can mark it as UAT pass after code review

**Comment by Anziskavds** [comment]
Should it open as per the below screen or should it open on the amount screen? @Jasonvdb 

![IMG_32E66D250FF7-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a8662bf5-0248-4e26-bedf-2cd29edfa895)

**Comment by Jasonvdb** [comment]
@Anziskavds that screen is correct. They still go through the same flow, just the details are already filled in

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14 on an iPhone 7. Please see above screenshot.
