### ISSUE TITLE
Launch QA: Onboarding: If user does not pin set up on the device, user is unable to start the app

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#343]
**Description**
I didn't have a pincode set to unlock my ipad. The app couldnt start because it couldnt use my “unlocking” method. After I set up a pin, the app started. 

**Smartphone:**
Network: rincewind
Phone: iPad 6
iOS: 13.4
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-04-29_21-22-49-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4556699/2020-04-29_21-22-49-bug-report.zip)

**Comment by talmahaj** [comment]
@Tas4tari wasn't this fixed in the last release?

**Comment by talmahaj** [comment]
Built, that is -- not fixed

**Comment by Tas4tari** [comment]
Yes built, should be in UAT @Jasonvdb can confirm if we can move this

**Comment by Jasonvdb** [comment]
Yup, think there were multiple issues for this. But it's in prod

**Comment by Anziskavds** [comment]
Tested on iOS. What is the expected behavior? @Jasonvdb @Tas4tari @talmahaj 

I removed my pin and fingerprints, downloaded the app again, and got the below two screens. It didn't go anywhere further than the last screenshot. After clicking on "Secure with pin" I receive "There is no biometry" and it just continues like this I am unable to go any further from the "There is no biometry" screen.

![IMG_A28C8F0BA5FB-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d37cf9c3-7876-41d2-89ab-7029cefe63ce)

![IMG_889BB8FCFA0D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3ad9b0df-e33b-4202-96e1-b2d3f5d58276)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 (iPhone 7).

I received the below screen and after clicking on proceed I was able to finish installing the app and the app opened as expected.

![IMG_3F5890F8FE2F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/506cd5cf-e53a-4203-a056-d3e451f2084a)
