### ISSUE TITLE
App resubmission tasks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#367]
1. Change the "poster frame" for the video with the image frame here: https://nomatter.tari.com/tari-ext/pl/y85k95xfbfnpmmou6zt1zk4oia (@karim-tari to send other sizes required) -- be sure to do it in Safari, since that's the only browser that supports the feature)

2. Make the copy change to the alert mentioned in #302

3. Update the release notes to the following:

Shiny new features:
- Cancel any transaction that hasn’t yet been accepted by the recipient
- Long press the Emoji ID “Copy” button to copy the hex public key instead of emojis
- Pull to refresh on your transaction list to re-sync it

Boring but still useful:
- Fallback to device PIN when Touch ID or Face ID is unavailable
- Fix for UI issues on for smaller iPhones on transaction detail view
- Fix for bug causing the app to crash when entering an amount to send

Last but not least, the animations in the onboarding flow have been refined to make the first-time user experience snazzier and more intuitive.

For the latest protocol updates, visit tari.com/updates.

**Comment by Anziskavds** [comment]
Tested on iOS (iPhone 7). Majority tested successfully, I am unable to test 
" - Fallback to device PIN when Touch ID or Face ID is unavailable
- Fix for UI issues on for smaller iPhones on transaction detail view
- Fix for bug causing the app to crash when entering an amount to send" because I don't have a device to use for this testing.

![IMG_A1F3C4F0E06B-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b1eaf02e-9f76-445b-b611-20fd2985c2b4)

![IMG_FAABA43EC5C6-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/354785f9-3ba1-447c-96c5-bb0e1d6666bd)
