### ISSUE TITLE
[Feature] Backup & restore wallet: Back up prompt modal

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#407]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by talmahaj** [comment]
@Jasonvdb What do you think the trigger should be for the encrypted backup prompt, if they haven't already done so by then?

**Comment by talmahaj** [comment]
**Back up prompt modal**

**Acceptance Criteria**

- When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9
- When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android)
- The modals above should NOT appear if the user has already connected their cloud account
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

**Comment by talmahaj** [comment]
@Tas4tari can you add the above specs to the Android ticket too? Thanks!

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on version 0.3.0 on an iPhone 7. I'm closing off this card because I'm adding separate cards for the ones which tested unsuccessfully. @Jasonvdb @Tas4tari @talmahaj 

**Back up prompt modal**

**Acceptance Criteria**

- When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31 - **Tested successfully**
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9 - **Tested unsuccessfully. The same modal for the 3 transactions showed instead of the one as per the design. It was the 4th transaction accepted so it needed to show the pop-up message as per the design.**
- When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android) - **Tested successfully**
- The first two modals above should NOT appear if the user has already connected their cloud account. - **Tested successfully**
- The third modal about encrypted backups should only appear if user has cloud backups enabled AND does not have the backups encrypted yet - **Tested successfully**
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be - **Tested unsuccessfully. I was redirected to the first settings page and not the one in the above design.**

**Testpad Report:** [https://app.zenhub.com/files/213589121/536e2fa8-1d67-4d26-9015-3aa46ddac6d3/download](https://app.zenhub.com/files/213589121/536e2fa8-1d67-4d26-9015-3aa46ddac6d3/download)

**Screenshots:**


![IMG_0593.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8f7339e4-b437-4d32-b347-9fb5d3325185)

![IMG_0594.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/de0ff034-ee7d-4ee2-9e9c-d32f21f7d135)

![IMG_0595.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f60d2e4b-5ec9-4834-95cb-5fb0a0b728c7)

![IMG_0596.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d38d7046-2695-4207-8da3-d1dff2c219a1)

![IMG_0597.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7acd629f-04d5-4353-abb6-9e862814e4d4)

![IMG_0598.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c78fb887-e8ed-4093-b327-83d4ffd9af44)

![IMG_0599.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/01ebcf85-2de2-41a5-8272-98e3d8e77f47)

![IMG_0600.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c5735cbc-48a9-4032-8ce8-3f646036b43b)

![IMG_0601.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/97bd9694-c60a-4512-99c7-5f117b70b39c)

![IMG_0602.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c9fd39bf-6eca-4105-b276-513ee68bef5c)

![IMG_0603.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1d146bc9-c790-468a-aed5-7dc8ba8d67a2)

![IMG_0604.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/eef80b61-dae7-42da-ab66-126fb3bd5b99)

![IMG_0605.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/073917bd-ee61-46a6-a23e-f62d16f725e1)

![IMG_0606.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8795e258-27fe-4c7f-9544-f08bf7a3ffdf)

![IMG_0607.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b535c230-282b-4893-b7bb-370bc04b3af8)

![IMG_0609.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/51ab7517-28d2-46ea-bb3d-3376fdf70fb5)

![IMG_0610.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/962c7442-e8d3-4f6e-bf80-47c619068731)

![IMG_0611.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/80aa2b5d-73a4-422f-a142-cc9619b2dcff)
