### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#447]
Once the user has their cloud storage connected, we want to back up wallet regularly on behalf of the user without their having to think about it, and without draining their cellular data plan.

**Open Qs:**
How long does it take to back up on average?

**Design**
It's here! https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ef40c39f47783a0be5cc238

**Constraints**
- With MW, it's critical we have a successful backup happen after every single transaction or risk a completely borked wallet restoration
- iOS can only back up with the app open

**Acceptance Criteria: Behavior**

- Cloud backups
    - Back up to the cloud after every single transaction
    - When backup is being attempted/in progress/retried, status bar on tx list screen should always read "Backing up your wallet..." with success message appearing as "Backup successful!" before the status bar disappears
    - If backup fails due to network connectivity, it should automatically start trying again once connectivity restored until it succeeds
    - If cloud is out of storage AND user app is backgrounded, send them push notification reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" 
    - If cloud is out of storage AND user app is in foreground, show modal reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK" (they can always retry manually from settings after resolving the issue)
    - If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive"
    - If user has cloud storage disabled, show same push notif and modal as above but body of message should read "You do not have iCloud enabled on your device" or "You do not have Google Drive enabled on your device"
    - iOS Only
        - If user exits app during backup process, send them notification reading "Wallet Backup Incomplete" "Please reopen Tari Aurora to back up your recent transaction data to iCloud." Whether they tap the push notif or return to the app later, the backup should retry as soon as the app is foreground (with the corresponding status bar copy displaying again)
    - Android Only
        - Start a timer w/ each transaction so it only backs up after 5 min to avoid multiple backups per transaction whenever possible

**Acceptance Criteria: UI/UX changes**

Settings Screen
- Change the “Back up wallet” setting in the security section to read “Wallet Backups” so it’s clearer you can go there to change your settings/see backup status
- To the right of “Wallet Backups,” Instead of a green or red indicator as to whether the user has connected iCloud, let’s instead have an indicator and a label that tells the user the current status of the backups: “Up to date” or “Out of date” or “In progress”
- Beneath “Wallet Backups,” add “Last successful backup: Mon D YYYY at HH:MM AM/PM”

Wallet Backups Screen
- iCloud backups should now display as a toggle. It’s switched off for new users, and then switched on once the user enables iCloud. User can switch it off to prevent the app from continuing to back up to iCloud (though it doesn’t delete the prior backups, that’s what the red link at the bottom is for!)
- New item called Back Up Now should be added that when tapped, forces a backup if one is not already in progress. Next to that item on the right, the same red/green/gray label and indicator from the prior screen should be added, and below it the same last backup timestamp as on the prior page should be added.

**Comment by talmahaj** [comment]
@kukabi @Jasonvdb @CjS77 I've edited this ticket to reflect today's convos. Anything you see missing/incorrect?

Another question: What are all the cases in which a backup may fail?  E.g.
- No network connectivity
- In iOS, user backgrounds the app
- ....

I'm no longer confident that notifying the user after a couple of retries is the best route, given we'd need some UX for what happens after we notify them (that is, do they have to hit some button to try again? not ideal) and that could add confusion.   I'm also a bit worried about how annoying it'll be for iOS users to have to wait for things to back up after every single transaction (esp. if they don't understand the technical side of why it's necessary)... Hmmmm.

**Comment by kukabi** [comment]
`Start a timer w/ each transaction so it only backs up after 5 min to avoid multiple backups per transaction whenever possible`

I think this applies to iOS as well.

**Comment by kukabi** [comment]
@talmahaj In addition to `Up to date`, `Out of date` and `In Progress` there is a fourth state in which the app is checking the backup status by querying the cloud, looks like `In Progress` but they're not the same. And a fifth state only on Android where GDrive hasn't been setup (authorized) on the device yet.

**Comment by kukabi** [comment]
Just as a note: we only have a single backup file at a time. Older backup files are stale and of no use.

**Comment by kukabi** [comment]
This at first sight can be confused with iCloud/GDrive password imo:

![Screen Shot 2020-06-25 at 07 55 23](https://user-images.githubusercontent.com/2969501/85656291-4b7e6100-b6b9-11ea-9c81-ec583a81e635.png)

Also it's just below iCloud in the menu, so i think it may be mistaken for the cloud pass itself:

![Screen Shot 2020-06-25 at 07 56 09](https://user-images.githubusercontent.com/2969501/85656410-62bd4e80-b6b9-11ea-9888-b5d3133ca093.png)

**Comment by talmahaj** [comment]
Descoping for now

- Local backups
    - ONLY IF cloud backup is encrypted, make silent local backup after every transaction.

**Comment by talmahaj** [comment]
> @talmahaj In addition to `Up to date`, `Out of date` and `In Progress` there is a fourth state in which the app is checking the backup status by querying the cloud, looks like `In Progress` but they're not the same. And a fifth state only on Android where GDrive hasn't been setup (authorized) on the device yet.

Hmm... what do you think about using "Checking backup status..." for that fourth state?

Also, would the below bullet from the spec not cover that last Android case you mention?
"If user has cloud storage disabled, show same push notif and modal as above but body of message should read "You do not have iCloud enabled on your device" or "You do not have Google Drive enabled on your device"

**Comment by talmahaj** [comment]
> I know it's in favor of the non-technical user to aviod the word `encrypt(ion)`, but this at first sight can be confused with iCloud/GDrive password imo:
> 
> ![Screen Shot 2020-06-25 at 07 55 23](https://user-images.githubusercontent.com/2969501/85656291-4b7e6100-b6b9-11ea-9c81-ec583a81e635.png)
> 
> Also it's just below iCloud in the menu, so i think it may be mistaken for the cloud pass itself:
> 
> ![Screen Shot 2020-06-25 at 07 56 09](https://user-images.githubusercontent.com/2969501/85656410-62bd4e80-b6b9-11ea-9888-b5d3133ca093.png)

@kukabi I've changed the copy to be more explicit, check out Zeplin and let me know what you think!

**Comment by Anziskavds** [comment]
Tested on iOS version 0.3.0 on an iPhone 7.

**Cloud backups**
- Back up to the cloud after every single transaction - **Tested successfully**
- When backup is being attempted/in progress/retried, status bar on tx list screen should always read "Backing up your wallet..." with success message appearing as "Backup successful!" before the status bar disappears - **Tested unsuccessfully** No backup statuses are showing.
- If backup fails due to network connectivity, it should automatically start trying again once connectivity restored until it succeeds - **Tested successfully**
- If cloud is out of storage AND user app is backgrounded, send them push notification reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" **Still need to be tested, I'm trying to fill up my storage to be able to test this**
- If cloud is out of storage AND user app is in foreground, show modal reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK" (they can always retry manually from settings after resolving the issue) -  **Still need to be tested, I'm trying to fill up my storage to be able to test this**
- If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive" - **Tested successfully** I received a pop-up error message "Failed to create backup. Can't connect to iCloud Drive services. Make sure that you are signed in with your Apple ID on this device and that iCloud is enabled." I didn't receive any push notification because the app is open.
- If user has cloud storage disabled, show same push notif and modal as above but body of message should read "You do not have iCloud enabled on your device" or "You do not have Google Drive enabled on your device" - **Tested successfully** I didn't receive any push notification because the app is open.
**iOS Only**
- If user exits app during backup process, send them notification reading "Wallet Backup Incomplete" "Please reopen Tari Aurora to back up your recent transaction data to iCloud." Whether they tap the push notif or return to the app later, the backup should retry as soon as the app is foreground (with the corresponding status bar copy displaying again) - **Tested successfully**

**Acceptance Criteria: UI/UX changes**

**Settings Screen**

- Change the “Back up wallet” setting in the security section to read “Wallet Backups” so it’s clearer you can go there to change your settings/see backup status - **Tested unsuccessfully** Still reads "Back up wallet".
- To the right of “Wallet Backups,” Instead of a green or red indicator as to whether the user has connected iCloud, let’s instead have an indicator and a label that tells the user the current status of the backups: “Up to date” or “Out of date” or “In progress” - **Tested unsuccessfully** I don't receive the "Out of date" status.
- Beneath “Wallet Backups,” add “Last successful backup: Month Date Year at HH:MM AM/PM”
Wallet Backups Screen - **Tested successfully**

- iCloud backups should now display as a toggle. It’s switched off for new users, and then switched on once the user enables iCloud. User can switch it off to prevent the app from continuing to back up to iCloud (ALL backups are deleted after the toggle was disabled) - **Tested successfully**
- New item called Back Up Now should be added that when tapped, forces a backup if one is not already in progress. Next to that item on the right, the same red/green/gray label and indicator from the prior screen should be added, and below it the same last backup timestamp as on the prior page should be added. - **Tested unsuccessfully** The "Out of date" status doesn't show.

**Screenshots**
![IMG_0582.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0b0561cc-e857-413a-9b74-610d2bb59034)

![IMG_0585.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0c2bdfad-8b10-453b-a69d-864436b428b8)

![IMG_0587.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9b6cf6b3-b2c1-4be3-8207-010d23ef5dc3)

![IMG_0580.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/edd0edfa-e3b8-40f0-aac9-73fa75b4e3c0)

![IMG_0581.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/134713da-beec-4681-8e7c-2aca5b67ead9)

![IMG_0578.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2a8e246f-19f0-4e41-80d9-92aadc64f254)

![IMG_0577.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/92e0cf9a-72f4-4409-849c-83bf3747dec0)

![IMG_0576.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4bc112d1-e7d1-4125-923f-4080dff965da)

![IMG_0573.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8ee1b0f0-6ab8-43dc-9e36-dbd500e961f7)

![IMG_0569.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/88163b48-612a-4e18-bef7-3eb11daab81b)

![IMG_0568.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/afac6e1b-bffa-4d9e-96eb-f41652ad685d)

![IMG_0565.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5518c6f3-89be-4907-9cb9-6360ac2cfad9)

![IMG_0564.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5d43e5dc-b629-465f-aa8f-723476624f37)

cc @talmahaj @Tas4tari @SerhiiShovkoplias @Jasonvdb

**Comment by Anziskavds** [comment]
Issues found while testing this card:

- Tested the out of date automated backups but I only receive the red exclamation mark and not the status “out of date”.
- Disabling the iCloud backups on the iPhone and going to the backup screen the iCloud backups are still enabled on the Tari App.
- Back up now button had a scheduled status next to it in grey but the "Out of date" status doesn't show only the red exclamation shows.
- When backup is being attempted/in progress/retried, status bar on tx list screen should always read "Backing up your wallet..." with success message appearing as "Backup successful!" before the status bar disappears - No statuses of backing up are showing on the tx list screen
- If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive” - I received a pop up error message "Failed to create backup. Can't connect to iCloud Drive services. Make sure that you are signed in with your Apple ID on this device and that iCloud is enabled." I have not received any push notifications because the app need to be open to test this.

Still to be tested:

- If cloud is out of storage AND user app is backgrounded, send them push notification reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" 
- If cloud is out of storage AND user app is in foreground, show modal reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK" (they can always retry manually from settings after resolving the issue).
I'm trying to get my storage filled up to be able to test this.

cc @talmahaj @Tas4tari @SerhiiShovkoplias @Jasonvdb

**Comment by Anziskavds** [comment]
Retested the ones which tested unsuccessfully on iOS on version 0.3.0 (113) on an iPhone 7 and found:

- Tested the out of date automated backups but I only receive the red exclamation mark and not the status “out of date”. - **Still tested unsuccessfully**
- Disabling the iCloud backups on the iPhone and going to the backup screen the iCloud backups are still enabled on the Tari App. **Tested successfully. When iCloud backups on the device are disabled the iCloud backups on the Tari app also disables** 
- When backup is being attempted/in progress/retried, status bar on tx list screen should always read "Backing up your wallet..." with success message appearing as "Backup successful!" before the status bar disappears - No statuses of backing up are showing on the tx list screen - **Tested successfully**


**Question for Tal on this before I can say if it tested successfully or unsuccessfully** - If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive” - I received a pop up error message "Failed to create backup. Can't connect to iCloud Drive services. Make sure that you are signed in with your Apple ID on this device and that iCloud is enabled." I have not received any push notifications because the app need to be open to test this.

![IMG_0605 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/be4436e1-a8b2-4a40-be9a-de3dfd5de0c2)

![IMG_0606 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7e5d2045-1cca-4472-b5f0-c1f9f3ba279b)

![IMG_0614.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/771b37eb-1cfc-420d-a0ea-37294646cb47)

![IMG_0615.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f6c6e77a-fa9a-4b52-806a-656be184bc9a)

**Comment by Anziskavds** [comment]
Feedback on the question i had for Tal. She's happy with the current behavior.

- If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive” - I received a pop up error message "Failed to create backup. Can't connect to iCloud Drive services. Make sure that you are signed in with your Apple ID on this device and that iCloud is enabled." I have not received any push notifications because the app need to be open to test this - **Tested successfully**

**Comment by Anziskavds** [comment]
This card is still open because the two requirements on the filled up storage still need to be tested. I'm just struggling to get my cloud storage filled up on the iPhone. As soon as the storage is filled up I'll test these two requirements.

**Still to be tested:**

- If cloud is out of storage AND user app is backgrounded, send them push notification reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full"
- If cloud is out of storage AND user app is in foreground, show modal reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK" (they can always retry manually from settings after resolving the issue)

cc @Tas4tari

**Comment by Anziskavds** [comment]
As discussed in Stand up on 2020/07/27, Tal said we should leave the out of storage requirements for now seeing that it is difficult to get the iCloud storage filled up for testing. Separate tickets for other issue found was added to Github so I'm closing off this card.
