### ISSUE TITLE
Wrong font for backup password text input fields 

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#508]
**Describe the bug**
Backup password & confirm text fields do not display with Avenir-family font.

**To Reproduce**
Go to the password setting screen & observe the placeholder text inside the text fields.

**Screenshots**
![IMG_8500](https://user-images.githubusercontent.com/2969501/88392786-48b08200-cdc5-11ea-8907-cb99437202a4.PNG)

**Comment by Anziskavds** [comment]
@kukabi How will I know if it is the correct font? iI can see the "enter password" and "change password" section looks a bit different but I don't know what font it is. I also see it no longer shows, "enter password" it shows "create password", is this expected behavior? @Tas4tari @SerhiiShovkoplias 

Tested on iOS on version 0.3.0(118) on an iPhone 7.
![IMG_B984FE3B0CCA-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/dc2fa946-e9ff-4ec5-ab19-36e2d0393b9d)

**Comment by Tas4tari** [comment]
@Anziskavds As per the designs it should say "Create a Password" which is correct. You can confirm that with the designs on Zeplin

**Comment by Anziskavds** [comment]
@Tas4tari Perfect, I saw that on the designs but just wanted to confirm before I assume it's correct and might have missed something that it should've been "Enter" instead of "Create".

@kukabi Will you please let me k ow how I can be sure that it it the correct font as expected?

**Comment by kukabi** [comment]
@Anziskavds yes they're both correct now.

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(118) on an iPhone 7. 
![IMG_B984FE3B0CCA-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/63f76bda-9d11-4c66-aefb-89d4a0e5b934)
