### ISSUE TITLE
When a scheduled backup has failed, send the user a push notification alerting them that the backup has failed

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#516]
**Description:**
If a scheduled backup has failed, send the user a push notification informing them the backup failed to complete, currently iOS displays as a modal and we would like this changed to a push notification

**Comment by Jasonvdb** [comment]
There are no push notifications when the app is open. That's what the modal is for. If the user backgrounds the app and the backup is unable to complete then they receive this local push notifications.

![IMG_3495](https://user-images.githubusercontent.com/5300488/88529175-ec857200-cfff-11ea-8288-6320b165887a.PNG)

**Comment by kukabi** [comment]
@Jasonvdb did you follow the discussion re this issue in the last product standup? We agreed to display notifications if the failed backup is not user-triggered, i.e. it's a scheduled backup.

**Comment by kukabi** [comment]
I don't feel strongly either way, and I stated this in the standup, but let's decide.

**Comment by Anziskavds** [comment]
@kutsal @jay What was the final decision on this? I'm receiving the below push notification when a scheduled backup didn't finish and I backgrounded the app. Is this the expected behavior?

![IMG_0751.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a7a64685-758e-490d-847f-2744d0c9c753)

![IMG_0752.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/af04d7f0-6b83-4c97-8be5-9f76320c9837)

![IMG_0753.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5201af50-4eed-46e5-a6ec-5159bb764a4f)

![IMG_0754.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9273b0ca-762a-4670-971d-0fdab9948221)

![IMG_0755.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/99563a68-877f-4dca-8b4e-9e826f1fe5b6)

**Comment by kukabi** [comment]
@Anziskavds This is the expected behaviour for the current release. PR #519 will cause the app to display a push notification if a scheduled backup fails when the app is foregrounded. Current release displays a modal dialog in this case.

**Comment by Anziskavds** [comment]
@kukabi Okay perfect, thank you. So I can close off this card. Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0751.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a7a64685-758e-490d-847f-2744d0c9c753)

![IMG_0752.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/af04d7f0-6b83-4c97-8be5-9f76320c9837)

![IMG_0753.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5201af50-4eed-46e5-a6ec-5159bb764a4f)

![IMG_0754.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9273b0ca-762a-4670-971d-0fdab9948221)

![IMG_0755.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/99563a68-877f-4dca-8b4e-9e826f1fe5b6)
